hidden symbol removed
SyntaxError: /Users/admin/.rvm/gems/jruby-head@torquebox/bundler/gems/devise_ldap_authenticatable-6a44c6b8cefd/lib/devise_ldap_authenticatable/model.rb:1: Invalid char `\273' ('»') in expressionï»¿require 'devise_ldap_authenticatable/strategy'